name: "Cleanup Preview"

on:
  pull_request:
    types: [ closed ]

env:
  GITHUB_PR_NUMBER: "${{github.event.number}}"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Pull release
      uses: actions/checkout@v2
      with:
        repository: ysndr/beta
        ref: gh-pages

    - name: Remove Preview
      run: |
        ls -la
        [ -d ./${{ env.GITHUB_PR_NUMBER }} ] && git rm -r ./${{ env.GITHUB_PR_NUMBER }}
        ls -la


    - name: Push
      uses: crazy-max/ghaction-github-pages@v2
      with:
        repo: ysndr/beta
        target_branch: gh-pages
        build_dir: ./.
        committer: github-ci <notifications+ci-blog@ysndr.de>
        keep_history: true
      env:
        GH_PAT: ${{ secrets.DEPLOY_TOKEN }}
