name: "Build Site and Deploy"

on:
  pull_request:
    types: [ closed ]

env:
  GITHUB_PR_NUMBER: "${{github.event.number}}"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Pull release
      uses: actions/checkout@v2
      with:
        repo: ysndr/beta
        ref: gh-pages

    - name: Remove Preview
      run: |
        [[ -d ./$GITHUB_PR_NUMBER ]] && rm -r $GITHUB_PR_NUMBER


    - name: Push
      uses: crazy-max/ghaction-github-pages@v2
      with:
        repo: ysndr/beta
        target_branch: gh-pages
        build_dir: ./.
        committer_name: github-ci
        committer-email: notifications+ci-blog@ysndr.de
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
